---
format: pdf
---


# Schemas
Students (<u>name</u>, major, classYear, dorm)

Clubs (<u>name</u>, category, meetingLocationName, presidentName)

Locations (<u>name</u>, building, capacity)

Events (<u>title, eventDate, startTime</u>, clubName, locationName, organizerName, cost)

Attendance (<u>eventTitle, eventDate, startTime, studentName</u>)

# 1
```{sql}
SELECT name, presidentName
FROM Clubs
INNER JOIN Events ON Events.clubName = Clubs.name
INNER JOIN Attendance ON Events.title = Attendance.eventTitle 
  AND Events.eventDate = Attendance.eventDate
  AND Events.startTime = Attendance.startTime
WHERE studentName = 'Harry Potter'
AND Event.eventDate BETWEEN '2026-01-01' AND '2026-12-31'
```

# 2
```{sql}
SELECT name
FROM Students
EXCEPT
SELECT studentName
FROM Attendance
INNER JOIN Events ON Events.title = Attendance.eventTitle
INNER JOIN Clubs ON Events.clubName = Clubs.name
WHERE Clubs.category = 'Herbology'
AND Event.eventDate BETWEEN '2026-01-01' AND '2026-12-31'
```


# 3
```{sql}
SELECT name
FROM Students
INNER JOIN Attendance ON name = Attendance.studentName
INNER JOIN Events ON Events.title = Attendance.eventTitle
INNER JOIN Clubs ON Events.clubName = Clubs.name
WHERE NOT Clubs.category = 'Herbology'
AND Event.eventDate NOT BETWEEN '2026-01-01' AND '2026-12-31'

```

# 4
```{sql}
SELECT title
FROM Events
GROUP BY title
HAVING COUNT(*) >= 2
```

# 5
```{sql}
SELECT COUNT(*) as numEvents
FROM Attendance
INNER JOIN Events ON Events.title = Attendance.eventTitle 
  AND Events.eventDate = Attendance.eventDate
  AND Events.startTime = Attendance.startTime
WHERE studentName='Harry Potter'
  AND locationName='Gryffindor Common Room'

```

# 6
```{sql}
SELECT clubName, COUNT(*) as numAttendences
FROM Events
INNER JOIN Attendance ON Events.title = Attendance.eventTitle 
  AND Events.eventDate = Attendance.eventDate
  AND Events.startTime = Attendance.startTime
WHERE Attendance.studentName = 'Harry Potter'
GROUP BY Events.clubName
```


# 7
```{sql}
SELECT DISTINCT studentName
FROM Attendance
WHERE NOT EXISTS(
  SELECT studentName
  FROM Attendance
  INNER JOIN Events ON Events.title = Attendance.eventTitle 
    AND Events.eventDate = Attendance.eventDate
    AND Events.startTime = Attendance.startTime
  INNER JOIN Locations ON Events.locationName = Locations.name
  WHERE NOT Locations.building = 'Gryffindor Tower'
);
```

# 8
```{sql}
SELECT Events.locationName, Events.clubName
FROM Events
LEFT JOIN Attendance ON Events.title = Attendance.eventTitle 
  AND Events.eventDate = Attendance.eventDate
  AND Events.startTime = Attendance.startTime
GROUP BY Events.locationName, Events.clubName
HAVING COUNT(*) = COUNT(Attendance.studentName)
```


# 9
```{sql}
SELECT DISTINCT e.clubName
FROM Events as e
WHERE e.cost > ALL(
  SELECT e2.cost
  FROM Events as e2
  WHERE e2.clubName='Slug Club'
)
```

# 10
```{sql}
SELECT DISTINCT studentName
FROM Attendance
INNER JOIN Events ON Events.title = Attendance.eventTitle 
  AND Events.eventDate = Attendance.eventDate
  AND Events.startTime = Attendance.startTime
INNER JOIN Clubs ON Clubs.name = Events.clubName
WHERE Clubs.category = 'Herbology'
GROUP BY Attendance.studentName
HAVING Count(DISTINCT Clubs.name) = (
  SELECT COUNT(*)
  FROM Clubs
  WHERE Clubs.category = 'Herbology'
)
```


# 11
Find the name of the location of events and the number of events where the event was hosted by the 'Slug Club' and the location was used at least 5 times. In other words, find the name of locations and the number of times an event was hosted by the 'Slug Club' and the location was used at least 5 times.

# 12
Find the distinct names of all the clubs who hosted events where their event location was at 'Gryffindor Common Room', the event was hosted in 2026 and the costs of the events where greater than all of the costs of events hosted by clubs under the name 'Slug Club'
