---
format: pdf
---

# 1
For $\lambda (G) \leq \gamma (G)$, since the minimum degree of $G$ is $\gamma (G)$ then there is at least one vertex with that many edges. Thus, we can have a disconnected graph by removing the edges for this minimum degree node. Now we know that this is a solution for creating a disconnected graph by removing $\gamma (G)$ edges and we know that $\lambda (G)$ is the least amount of edges needed to create a disconnected graph so thus $\lambda (G) \leq \gamma (G)$

For $\kappa (G) \leq \lambda (G)$, we know our optimal $\lambda (G)$ essentially creates a cut of $G$ and the edges used for the edge connectivity as the cut edges. Now only looking at the cut edges, we can look at this as a bipartite subgraph and finding a vertex cover of this graph if we remove those vertices from $G$ we would have a disconnected graph because the vertex cover has at least one vertex per edge so removing all of these vertices would remove all the cut edges. We have the naive vertex cover of one vertex per edge but a minimum vertex cover here would likely be less than $\lambda (G)$. Thus this vertex cover would lead to a disconnected graph by removing vertices and is less than or equal to $\lambda (G)$ therefore the optimal $\kappa (G)\leq \lambda (G)$


# 2
I worked on finding a graph from the class on finding $k$-regular simple graphs without a $1$-factor. In class it was me Nate and Nico working on it (like 2ish weeks ago?) and found the $k$ is even case to be trivial but the odd case to be rather tricky. The difference between this problem and that is here we remove a single vertex as opposed to always removing pairs of vertices. Using the logic from those problems here is my solution:


We have 2 pentagons (5 nodes and currently $2$-regular) and we add 2 edges to each pentagon such that we have 4 vertices of degree 3 and one vertex still at degree 2.

Now we can connect the two pentagons with an edge to the 2 degree 2 nodes creating a bridge between the pentagons. Now removing either of these bridge vertices will disconnect the graph. Now we have shown that this graph is $3$-regular and has a connectivity of $1$.


# 3
I am going to make the assumption that for any given edge there are ONLY two cycles that use it and are disjoint. The reason being for a fully connected $5$ vertex graph has any given edge having $3$ disjoint cycles besides that edge BUT (to my knowledge) is actually $4$ edge connected. Note that there my assumption can assume more than two cycles BUT it assumes at MOST two DISJOINT cycles. 

For an arbitrary edge $e=(u,v)$ since there are two cycles that use $e$ and are otherwise disjoint, then $\exists$ two disjoint paths from $u$ to $v$ that do not contain $e$. So after removing $e$, we know that we can have our 2 disjoint paths but there could exist more than 2 paths from $u$ to $v$. For an arbitrary path $p$ that is not one of our disjoint paths, it must use at least one edge in at least one of the two existing disjoint paths from $C_1,C_2$. So removing one of these intersecting edges from $p$ would remove $p$ and say $C_1$ from reaching $v$ from $u$ then we apply some similar logic for an arbitrary path $p_2$ for $C_2$ to make it so that $u$ and $v$ are no longer connnected thus $G$ has an edge connectivity of $3$. 

But suppose $p_2$ and $p$ are both only sharing an edge with the path from $C_1$ and that the edges they share with $C_1$ are disjoint. Then this would create a contradiction becase then $p$ and $p_2$ would create two disjoint paths from $u$ to $v$ and now adding back in $e$ we have three cycles instead of 2 ($p+e,p_2+e,C_2$). Therefore $p$ and $p_2$ must share at least one edge with eachother. 
