---
format: pdf
---

# 2.1

$E=$ {at least one die is even}

$SUM8=$ {sum of 2 die is 8}

$|\Omega|=6^2=36$

$|SUM8|=5$ [(2,6), (3,5), (4,4), (5,3), (6,2)]

$P(SUM8)= \frac{5}{36}$

$|SUM8 \cap E| = 3\rightarrow P(SUM8\cap E) = \frac 1 {12}$

$P(E|SUM8) = \frac{P(E\cap SUM8)}{P(SUM8)} = \frac{1}{12}\frac{36}{5}= \frac{3}{5}$

Alternatively:

$P(E|SUM8)= \frac{|SUM8\cap E|}{|SUM8|} = \frac{3}{5}$

# 2.6
## a
$A=$ {Alice watches TV}

$B=$ {Betty watches TV}

$P(A)=0.6$

$P(B|A)=0.8 = \frac{P(AB)}{P(A)}$

$P(AB)= P(B|A)*P(A) = 0.8*0.6=0.48$

## b
$P(B|A^c)=0$ because the TV is not on

Therefore $P(B)= P(AB)= 0.48$

## c
$AB^c=$ {Alice watches TV and Betty does not}

$P(B^c|A) = \frac{P(AB^c)}{P(A)}=1-P(B|A)=0.2$

$P(AB^c)= P(B^c|A)*P(A)=0.2*0.6=0.12$


# 2.11
$C=$ {customer is careful}

$P(C)= 0.8$

$R=$ {customer is reckless}

$P(R)= 0.2$

$A=$ {customer caused an acciident}

$P(A|C) = \frac{P(AC)}{P(C)}=0.01$

$P(A|R) = \frac{P(AR)}{P(R)}=0.04$

$A = AC\cup AR$

$P(A) = P(AC) + P(AR) - P(AC\cap AR)$

$P(AC)= 0.01*0.8=0.008$

$P(AR) = 0.04 *0.2 = 0.008$

$P(AC\cap AR)=0$ because $C\cap R= \phi$

$P(A) = 0.016$

$P(C|A)= \frac{P(A|C)P(C)}{P(A)}=\frac{0.01*0.8}{0.016}=\frac12$

# 2.14
$P(A\cap B)=0$ because they are disjoint. So $P(A)P(B)=P(A\cap B)$ for independence. Thus $P(A)=0 \lor P(B)= 0$ for independence. 

# 2.48
There is a lot of missing information so I will proceed with this question with the following assumptions:

1. There is only a single perpetrator and they live in the town
2. Only one person is going to be choosen as guilty
3. Kevin is NOT the perpetrator (someone else is the perpetrator) and he lives in the town
4. There is a 0% false negative rate with the DNA matching (the perpetrator is guranteed to have their DNA match)
5. There is no evidence on the perpetrator (or anyone) so anyone DNA matched is equally likely to be choosen as guilty
6. Everyone in the town had their DNA tested against the DNA in the crime scene

Given the rules of the problem there will always be 2 DNA matches of the 100,000 (Kevin and the perpetrator). Meaning there are 99,998 other people to potentially have their DNA tested.

$2MATCHES=$ {2 people had their DNA match} 

$3MATCHES=$ {3 people had their DNA match} 

...

$100000MATCHES=$ {100000 people had their DNA match} 

> Note that these events are disjoint

$Kevin=$ {Kevin is guilty}

$P(Kevin|2MATCHES)= \frac 12$

$P(Kevin|XMATCHES) = \frac 1X$

$P(Kevin)= P(Kevin|2MATCHES)P(2MATCHES) + ... + P(Kevin|100000)P(100000MATCHS)$ 

$\rightarrow P(Kevin)= \sum_{i=2}^{100000} P(Kevin|iMATCHES)P(iMATCHES)$

$P(XMATCHES)=\frac{1}{10,000}^{X-2}\frac{9,999}{10,000}^{99,998-X}$

$\rightarrow P(Kevin) = \sum_{i=2}^{100,000} \frac1 i \frac{1}{10,000}^{i-2} \frac{9,999}{10,000}^{99,998-i}=$

Below is the python code to determine the result of the summation

```{python}
print("P(Kevin)="+str(sum([1/x * 0.0001**(x-2) * 0.9999**(99998-x) for x in range(2,100000)])))
```

$.$

# 2.54
## a 
Yes it is possible to determine $P(A)$

$P(AB)= \frac13 P(B)$

$P(AB^c)= \frac 13(1-P(B))$ 

$P(A) = P(AB)+  P(AB^c)+ P(AB\cap AB^c)= \frac13 P(B) + \frac 13(1-P(B)) +0 =\frac13$

## b
Yes $A$ and $B$ are independent because $P(A| B) = \frac 13 = P(A)$

