---
format: pdf
---

# 2.23
## a
$P(1N)= 0.95^1$

$P(7N)=0.95^7=0.698337$

## b
September has 30 days.

$P(Sept=2)= \binom{30}{2} (0.05)^2 (0.95)^28=0.2586367$

## c
$10N=$ {10 Days of no accidents}

Therefore at least $1$ accident in 10 days is $10N^c$

$P(10N^c|4N)= 1-P(6N)$ because we know that the accident must occur within the last 6 days

$\rightarrow P(10N^c|4N)=1-(0.95^6)=0.2469$

$P(10N^c \cap 4N)= P(10N^c|4N)*P(4N)=0.2469*0.95^4=0.215769$

# 2.28
## a
Hypergeometric distribution, $X~ Hypergeom(52,4,13)$

## b
Binomial distribution, $X~bin(50,1-\frac{48!39!}{35!52!})\rightarrow X~bin(50, \frac{14498}{20825})$

## c
Binomial distribution, $X~bin(50, \frac{12!39!}{51!}\rightarrow X~bin(50,\frac{1}{8255176274800})$

## d
Hypergeometric distribution, $X~ Hypergeom(52, 13, 13)$

# 2.47
$P(2F)=\frac{55}{80} \frac{54}{79}=\frac{297}{632}$

# 2.66
We can treat this problem as a binomial distribution with $X~bin(n,\frac16)$ and we are solving for an $n$ with the highest resulting probability.

$P(X=2)=\binom n 2 (\frac16)^2(\frac56)^{n-2}$ for $n=2,3,...,40$

I will use the python code below to solve for $n$:

```{python}
from math import comb
bestProb = 0
bestRolls = 0
for n in range(2,40):
  prob=(comb(n,2) * ((1/6)**2) *((5/6)**(n-2)))
  if prob > bestProb:
    bestProb = prob
    bestRolls = n
print(f"Optimal number of rolls is {bestRolls} resulting in a probability of {bestProb}")
```

Therefore the optimal number of rolls is actually $11$ resulting in a probability of $0.296$

# 2.71
## a
Let $A_n$ denote the set where the $n$th flip is tails and $A_1A_2...A_n$ represent a $n$ consecutive tails flips.

Let $P(B)$ be the probability the coin is biased.

The question is solving for $P(B|A_1), P(B|A_1A_2), P(B|A_1...A_n)$

$P(B|A_1)= \frac{P(A_1|B)P(B)}{P(A_1)}$

From the problem (and exercise 2.38) we have the following values:

- $P(A_i)=\frac{51}{100}$
- $P(B)= \frac1{10}$
- $P(A_1|B)= \frac35$

Plug those in to the above equation:

> $P(B|A_1)= \frac{P(A_1|B)P(B)}{P(A_1)}=\frac35\frac{1}{10}\frac{100}{51}=\frac{2}{17}$

For $P(B|A_1A_2)$:

> $P(A_1A_2|B)= \frac{3}{5}^2=\frac{9}{25}$
>
> $P(A_1A_2)= \frac12^2 \frac9{10} + \frac35^2 \frac1{10} =\frac{261}{1000}$
>
> $P(B|A_1A_2)= \frac{P(A_1A_2|B)P(B)}{P(A_1A_2)}=\frac{9}{25}\frac{1}{10}\frac{1000}{261}=\frac{4}{29}$

For $P(B|A_1...A_n)$:

> $P(A_1...A_n|B)= \frac35^n$
>
> $P(A_1...A_n)= \frac12^n \frac9{10} + \frac35^n \frac1{10}$
>
> $P(B|A_1...A_n)=\frac{P(A_1...A_n|B)P(B)}{P(A_1...A_n)}=\frac{\frac35^n\frac1{10}}{\frac12^n\frac{9}{10} + \frac35^n\frac1{10}}=\frac{\frac35^n}{9\frac12^n+\frac35^n}$

## b
This question is for what $n$ is $P(B|A_1...A_n)\geq 0.9$?

Below is the python code to help figure this out:

```{python}
n=1
p=2/17

while(p < 0.9):
  n+=1 
  p = ((3/5)** n) / (9*((1/2)**n) + (3/5)**n)
print(f"n = {n}: p = {p}")
```

Thus after 25 straight tails we can say that with 90% probability that the coin is biased.

## c
$P(A_{n+1}|A_1...A_n)=P(A_{n+1}|B)P(B|A_1...A_n) + P(A_{n+1}|F)P(F|A_1...A_n)$

$\rightarrow P(A_{n+1}|A_1...A_n)=P(A_{n+1}|B)P(B|A_1...A_n) + P(A_{n+1}|B^c)P(B^c|A_1...A_n)$

$\rightarrow P(A_{n+1}|A_1...A_n)=\frac35 \frac{\frac 35^n}{9\frac12^n + \frac35^n} + \frac12 (1-\frac{\frac35 ^n}{9\frac12^n + \frac35^n})$

## d
$\lim_{n\rightarrow\infty} P(A_{n+1}|A_1...A_n)=\frac35$ because $\lim_{n\rightarrow\infty}P(B|A_1...A_n)=1$.

# 2.81
$|\Omega| = 669^n$

$U=$ {Unique birthdays}

$U^c=$ {At least 2 with the same birthday}

$|U|= P_{n}^{669}$

$P(U^c) = 1-\frac{|U|}{|\Omega|} = 1- \frac{669!}{669^n (669-n)!}$

Now for what $n$ is $P(U^c) \geq 0.9$?

Again using python:

```{python}
from math import perm
n=0
p=0
while (p< 0.9):
  n+=1
  p = 1 - (perm(669,n) / (669**n))
print(f"n = {n}: p = {p}")
```

Therefore the $n$ resulting in $P(U^c)>0.9$ is $n=56$, in other words a group of martians of size $56$ has a $0.9$ probability of having at least two matching birthdays.
