---
format: pdf
---

# 6.6
Let $X,Y$ be jointly continuous with the joint probability density function:

$f(x,y)= xe^{-x(1+y)}$ for $x,y>0$

## a 
Find the marginal density function of $X$ and $Y$

```{python}
from sympy import Symbol, integrate
from scipy.integrate import dblquad
import math

x = Symbol("x")
y = Symbol("y")

print(integrate(x*math.e**(-x-x*y), y))
```

> $f_X(x) = \int_0^{\infty} xe^{-x-xy} dy$
>
> $\rightarrow e^{-x}\int_0^\infty xe^{-xy}dy$
>
> $\rightarrow e^{-x}(-e^{-xy}|_0^\infty)$
>
> $\rightarrow e^{-x}(0 - (-e^{-x}))=e^{-2x}$

```{python}
print(integrate(x*math.e**(-5*x), x))
```

The package didn't want to integrate with $y+1$ so i swapped that for $5$


> $f_Y(x) = \int_0^{\infty} xe^{-x-xy} dx$
>
> $f_Y(x) = (-\frac{x}{(y+1)} - \frac{1}{(y+1)^2})e^{-x(y+1)} |_0^\infty$

> $f_Y(x) = (-\frac{x(y+1)+1}{(y+1)^2})e^{-x(y+1)} |_0^\infty$
>
> $0-\frac{0(y+1)+1}{(y+1)^2}=\frac1{(y+1)^2}$

## b
Calculate $E(XY)$

$E(XY)= \int_0^\infty \int_0^\infty x^2y e^{-x(y+1)}dydx$

$\rightarrow \int_0^\infty (x^2e^{-x})\frac{e^{-xy}}{x^2}|_0^\infty dx$ 

Note I removed the $uv$ term as it goes to $0$ with the bound integral

$\rightarrow \int_0^\infty e^{-x-xy}|_0^\infty dx$ 

$\rightarrow \int_0^\infty e^{-x} dx$ 

$\rightarrow -e^{-x}|_0^\infty= 1$

## c
Calculate $E(\frac{X}{1+Y})$

$E(\frac{X}{1+Y})= \int_0^\infty \int_0^\infty \frac{x^2}{1+y} e^{-x(y+1)}dxdy$

Integral calculator:

$\int_0^\infty \frac{2}{(y+1)^4} dy$

Integral calculator

$\frac{-2}{3(y+1)^3}|_0^\infty=\frac23$

# 6.7
Consider the triangle with verticies $(0,0), (1,0), (0,1)$. Suppose that $(X,Y)$ is a uniformly choosen random point from this triangle

Since the area of the triangle is $2$, $f(x,y)=2$ if $(x,y)\in$ the Triangle

## a
Find the marginal density functions of $X$ and $Y$

$f_X(x)= \int_0^{1-x} 2 dx = 2(1-x)$

$f_Y(y)= \int_0^{1-y} 2 dy = 2(1-y)$

## b
Calculate $E(X)$ and $E(Y)$

$E(X)= \int_0^1\int_0^{1-x} 2x dy dx= \int_0^1 2x-x^2 dx = x^2 -\frac13x^3 |_0^1 = \frac23$

$E(Y)= \int_0^1\int_0^{1-y} 2y dx dy= \int_0^1 2y-y^2 dy = y^2 -\frac13y^3 |_0^1 = \frac23$

## c
Calculate $E(XY)$

$E(XY)= \int_0^1\int_0^{1-x} 2xy dydx =\int_0^1 x(1-x)^2 dx = \int_0^1 x -2x^2 +x^3 \frac12 x^2 - \frac23 x^3 + \frac14 x^4 |_0^1 = \frac 1{12}$

# 6.11
Let $X$ have the density function $f_X(x)=2x$ for $0<x<1$ and $0$ else

Let $Y$ be uniformly distributed on the interval $1,2$

Assume $X,Y$ are independent

## a
Give the joint probability function of $(X,Y)$

$f(x,y)=f_X(x)f_Y(y)$

$f_Y(y)= 1$ for $y\in(1,2)$

$f(x,y)= 2x$ for $x\in(0,1)\land y\in(1,2)$ and $0$ else

## b
Calculate the probability $P(Y-X\geq \frac32)$

$2-\frac32=\frac12$ and $1-\frac32=-\frac12$ so $P(Y-X\geq \frac32)=\int_0^\frac12 \int_{x+\frac32}^2 2x dydx$

$\rightarrow \int_0^\frac12 4x - (2x^2 + 3x) dx$

$\rightarrow \int_0^\frac12 x - 2x^2 dx$

$\rightarrow \frac12 x^2 - \frac23 x^3|_0^\frac12$

$\rightarrow \frac18 - \frac1{12} = \frac1{24}$

# 6.18
Suppose that X and Y are integer valued random variables with joint probability mass function given by

$pX,Y (a, b) = \frac{1}{4a}$ for $1 \leq b \leq a \leq 4$

## (a)
Show that this is indeed a joint probability mass function.

Essentially, show $\sum\sum p(a,b)dadb = 1$

$\sum_{a=1}^4\sum_{b=1}^a \frac{1}{4a} = \sum_{a=1}^4 \frac1{4a}a  = \sum_{a=1}^4 \frac14 =1$


## (b)
Find the marginal probability mass functions of X and Y.

for $a,b\in{1,2,3,4}$

$p_X(a) = \sum_{b=1}^a \frac1{4a} = \frac14, \forall a$

$p_Y(b) = \sum_{a=b}^4 \frac1{4a} = \frac14 \sum_{a=b}^4 \frac1a$

>$p_Y(1)=\frac14 (1+\frac12+\frac13+\frac14)=\frac14\frac{25}{12}=\frac{25}{48}$

>$p_Y(2)=\frac14 (\frac12+\frac13+\frac14)=\frac14\frac{13}{12}=\frac{13}{48}$

>$p_Y(3)=\frac14 (\frac13+\frac14)=\frac14\frac{7}{12}=\frac{7}{48}$

>$p_Y(4)=\frac14 (\frac14)=\frac{1}{16}$

## (c) 
Find $P (X = Y + 1)$

$\sum_{a=2}^4 p_{X,Y}(a,a-1)=\frac18+\frac1{12}+\frac1{16}=\frac{13}{48}$
