---
format: pdf
---

# HW4 STAT 312

## 1
Suppose that the probability density function of a random variable $X$ is $f(x)=e^{-(x-4)},x>4$.

### A
Find the following probabilities:

#### 1
$P(X>1)$

> $P(X<1)=1$

#### 2
$P(2<X<5)$

> $P(2<X<5)=1-P(X\geq 5)=1-\int_{5}^{\infty}e^{-(x-4)}dx=1-e^{-(5-4)}=1-e^{-1}=0.632$

#### 3
$P(X>5)$

> $P(X>5)=P(X\geq 5)-P(5)=\int_{5}^{\infty}e^{-(x-4)}dx-0=e^{-(5-4)}=e^{-1}=0.368$

#### 4
Find $x$ such that $P(X<x)=0.9$

> $0.9=\int_{4}^{x}e^{-(x-4)}dx\rightarrow 0.9=-e^{-(x-4)}+e^{-(4-4)}\rightarrow ln(0.1)=-(x-4)\rightarrow x=4-ln(0.1)=6.303$

### B
Find $F(x)$

$$
F(x)=
\begin{cases}
0 & \text{for} \quad x \leq 4 \\
1-e^{-(x-4)} & \text{for} \quad 4< x \\
\end{cases}
$$

### C
Graph $F(x)$ and $f(x)$

> I used python to graph $F(x)$ and $f(x)$

```{python}
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(4, 10, 100)
f = np.exp(-(x-4))
F = 1 - np.exp(-(x-4))

plt.plot(x, f, color='blue')
plt.plot(x, F, color='red')
plt.xlabel('x')
plt.ylabel('f(x) and F(x)')
plt.title('f(x) and F(x)')
plt.legend(['f(x)', 'F(x)'])
plt.show()

```

### D
Find the mean of $X$

> $E(X)=\int_{4}^{\infty}x\cdot e^{-(x-4)}dx=-(x+1)e^-(x-4)|_{4}^{\infty}=(4+1)e^{0}=5$

## 2
Let $X$ be a continuous random variable with cumulative distribution function (cdf)
$$
F(x) =
\begin{cases}
0 & \text{for} \quad x < 0 \\
\frac{1}{6}x^2+\frac{1}{6}x & \text{for} \quad 0\leq x < 2 \\
1 & \text{for} \quad 2\geq x \\
\end{cases}
$$

### A
#### 1
$P(X>1)$

> $P(X>1)=1-P(X\leq 1)=1-F(1)=1-(\frac{1}{6}+\frac{1}{6})=\frac{2}{3}$

#### 2
$P(-1<x<1.5)$

> $P(-1<x<1.5)=F(1.5)-F(-1)=(\frac{1}{6}\frac{9}{4}+\frac{1}{6}\frac{3}{2})-0=\frac{3}{8}+\frac{1}{4}=\frac{5}{8}$

#### 3
$P(X>3)$

> $P(X>3)=1-P(X\leq 3)=1-F(3)=1-1=0$

### B
Find the probability density function of $X$

$$
f(x) =
\begin{cases}
0 & \text{for} \quad x < 0 \\
\frac{1}{3}x+\frac{1}{6} & \text{for} \quad 0\leq x < 2 \\
0 & \text{for} \quad 2\geq x \\
\end{cases}
$$

### C
Find the mean, variance and standard deviation of $X$

> $E(X)=\int_{-\infty}^{\infty}x\cdot f(x)dx=\int_{0}^{2}x(\frac{1}{3}x+\frac{1}{6})dx=\frac{1}{9}x^3+\frac{1}{12}x^2|_{0}^{2}=\frac{8}{9}+\frac{1}{3}=\frac{11}{9}$
>
> $V(X)=\int_{-\infty}^{\infty}(x-E(X))^2\cdot f(x)dx=\int_{0}^{2}(x-\frac{11}{9})^2(\frac{1}{3}x+\frac{1}{6})dx=\int_{0}^2 \frac{1}{3}x^3-\frac{35}{54}x^2+\frac{22}{243}x+\frac{121}{486}dx=\frac{x^4}{12}-\frac{35}{162}x^3+\frac{11}{243}x^2-\frac{121}{486}x=\frac{23}{81}$
>
> $\sigma = \sqrt{(V(X))} =\sqrt{\frac{23}{81}}=\frac{\sqrt{23}}{9}$