---
format: pdf
---

# P320 9-10 (Modified) (9 pt)
The heat evolved in calories per gram of a cement mixture is approximately normally distributed with a standard deviation of 2. We wish to test $H_0$ : μ = 100 versus $H_1$ : μ ≠ 100 with a sample of size 5. If the rejection region is defined as $\bar x$ < 98.5 and $\bar x$ > 101.5, then find

## a. $\alpha$ , the type I error probability;

> $\alpha = P(\text{type 1 error}) = P(\text{reject }H_0 \text{ when }H_0\text{ is true})$
>
> $=P(\bar x <98.5\lor\bar x > 101.5)$
>
> z = $\pm \frac{1.5}{2/\sqrt 5}=\pm 1.677$
>
> $=P(Z<-1.677) + P(Z>1.677)$
>
> $= 0.04648+0.04648=0.09296$

## b. $\beta$, the type II error probability, for the case when the true mean heat evolved is 103; and

> $\beta(103) = P(\text{type 2 error}) = P(\text{fail to reject }H_0 \text{ when }\mu = 103)$
>
> $=P(98.5 <\bar x < 101.5)$
>
> z_{low} = $\frac{-4.5}{2/\sqrt 5}=-5.031$
>
> z_{high} = $\frac{-1.5}{2/\sqrt 5}=-1.677$
>
> $=P(Z<z_{high}) - P(Z<z_{low})\rightarrow P(Z<-1.677)-P(Z<-5.031)$
>
> $=0.04648-0=0.04648$

## c. the power of the test when the true mean heat evolved is 103.

> $1-\beta(103)=0.95352$

# P330 9-42 (Modified) (17 pt)
Humans are known to have a mean gestation period of 280 days (from last menstruation) with a standard deviation of about 9 days. A hospital wondered whether there was any evidence that their patients were at risk for giving birth prematurely. In a random sample of 70 women from this hospital, the average gestation time was 274.3 days.

## a. Can you conclude that the sample data provides enough evidence that the average gestation time of all the patients at this hospital was less than 280 days at a significant level of 0.05? Use the 8-step critical region approach.

1. Identify the parameter of interest

> $\mu $

2. State the hypotheses to be tested.

> $H_0 =\mu = 280$
>
> $H_1 =\mu \leq 280$

3. Specify the level of significance α.

> $\alpha = 0.05$

4. Determine the test statistic and its distribution.

> z-test
>
> $z=\frac{\bar x-\mu}{\sigma /\sqrt n}=\frac{\bar x-280}{9/\sqrt{70}}$
>
> Assuming $H_0$ is true

5. Determine the rejection region.

> $z<-1.64$

6. Calculate the observed value for the test statistic.

> $z=\frac{\bar x-\mu}{\sigma /\sqrt n}=\frac{274.3-280}{9/\sqrt{70}}$
>
> $z= \frac{-5.7}{9/\sqrt 70}=-5.299$

7. Make a statistical decision.

> Reject $H_0$ because $z$ is in the reject region ($z<1.64$)

8. State the conclusion.

> At the $0.05$ significance level there is enough evidence to conclude that the population mean is less than $280$


## b. Can you use the P-value to conclude that the sample data provides enough evidence that the average gestation time of all the patients at this hospital was less than 280 days at a significant level of 0.05? Why or why not?

1. Identify the parameter of interest

> $\mu $

2. State the hypotheses to be tested.

> $H_0 =\mu = 280$
>
> $H_1 =\mu \leq 280$

3. Specify the level of significance α.

> $\alpha = 0.05$

4. Determine the test statistic and its distribution.

> z-test
>
> $z=\frac{\bar x-\mu}{\sigma /\sqrt n}=\frac{\bar x-280}{9/\sqrt{70}}$
>
> Assuming $H_0$ is true

5. Calculate the observed value for the test statistic.

> $z=\frac{\bar x-\mu}{\sigma /\sqrt n}=\frac{274.3-280}{9/\sqrt{70}}$
>
> $z= \frac{-5.7}{9/\sqrt 70}=-5.299$

6. Compute the p-value

> $P(z<-5.299)=0$

7. Make a statistical decision.

> Reject $H_0$ because P-value is less than $0.05$

8. State the conclusion.

> At the $0.05$ significance level there is enough evidence to conclude that the population mean is less than $280$

## c. Can you conclude that the sample data provides enough evidence that the average gestation time of all the patients at this hospital was less than 280 days at a significant level of 0.05 using an appropriate confidence interval? State you reason.

> $z_\alpha =1.64$
>
> The range for $\mu$ is $(-\infty, 274.3+1,64*9/\sqrt 70]=(-\infty, 276.06]$
>
> $\mu = 280$ is outside of this range
>
> At the $0.05$ significance level there is enough evidence to conclude that the population mean is less than $280$ because 280 is outside of the range of $\mu$

## d. What additional assumptions are necessary for the method you used in part a-c to be valid? Explain.

> Assumption of normality and random sampling

# Problem 3 (8 pt)
For the hypothesis test H0: μ = 10 against H1: μ > 10 with variance known and n = 15,

## a. Use table III to find the P-value for each of the following values of test statistic.
### (1) $z_0$ = - 2.05

>

### (2) $z_0$ = 1.84

>

## b. Use R to compute the P-values in part a. Attach the codes and output.
```{r}

```
