---
format: pdf
execute:
  eval: false
---

# HW 2
## 1
### e
Our original LP is as follows:

> $\max x_1 + x_2$

> s.t. $2x_1 + x_2 \leq 3$

>> $0\leq x_1,x_2 \leq 1$

This is equivalent to:

> $\max x_1 + x_2$

> s.t. $2x_1 + x_2 \leq 3$

>> $x_1 \leq 1$

>> $x_2 \leq 1$

>> $0\leq x_1,x_2$

Thus the dual is:

> $\min 3y_1 + y_2 + y_3$

> s.t. $2y_1 + y_2 \geq 1$

>> $y_1 + y_3 \geq 1$

>> $y_1,y_2,y_3 \geq 0$


Thus the complementary slackness conditions are as follows:

> $(2x_1+x_2-3)y_1 = 0$

> $(x_1-1)y_2 = 0$

> $(x_2-1)y_3 = 0$

> $(1-2y_1-y_2)x_1 = 0$

> $(1-y_1-y_3)x_2 = 0$


### f
```{python}
from docplex.mp.model import Model

mdl = Model()

y1 = mdl.continuous_var(name='y1', lb=0)
y2 = mdl.continuous_var(name='y2', lb=0)
y3 = mdl.continuous_var(name='y3', lb=0)

mdl.add_constraint(2*y1 + y2 >= 1)
mdl.add_constraint(y1 + x3 >= 1)

mdl.minimize(3*y1 + y2 + y3)

solution = mdl.solve()

print(mdl.export_as_lp_string())

print(solution)
```

This results in a $y^*$ as follows:

$$
y^* =
\begin{pmatrix}
0 \\
1 \\
1
\end{pmatrix}
$$

We can substitute the values of $y^*$ to our slackness conditions:

> $(2x_1+x_2-3)0 = 0$

>> $\rightarrow 0=0$

> $(x_1-1)1 = 0$

>> $\rightarrow x_1 = 1$

> $(x_2-1)1 = 0$

>> $\rightarrow x_2 = 1$

> $(1-0-1)x_1 = 0$

>> $\rightarrow 0=0$

> $(1-0-1)x_2 = 0$

>> $\rightarrow 0=0$

Therefore we end up with $x^*,y^*$ as follows:

$$
y^* =
\begin{pmatrix}
0 \\
1 \\
1
\end{pmatrix}
, x^* =
\begin{pmatrix}
1 \\
1
\end{pmatrix}
$$

We can also see that by strong duality these solutions result in their objective values being $2$ and equal. Thus these solutions are optimal.

## 3
### c
Our original LP is:

> $\min \gamma$

> s.t. $3x_1 + x_2 + x_3 + x_4 \leq \gamma$

>> $3x_1 + 4x_2 + 2x_3 + 2x_4 \leq 2\gamma$

>> $3x_1 + 4x_2 + 5x_3 + 3x_4 \leq 3\gamma$

>> $3x_1 + 4x_2 + 5x_3 + 6x_4 \leq 3\gamma$

>> $x_1 + x_2 + x_3 + x_4 = 1$

>> $x_1,x_2,x_3,x_4\geq 0$

Which can be rewritten as:

> $\max 0+0+0+0-\gamma$

> s.t. $3x_1 + x_2 + x_3 + x_4 - \gamma \leq 0$

>> $3x_1 + 4x_2 + 2x_3 + 2x_4 - 2\gamma \leq 0$

>> $3x_1 + 4x_2 + 5x_3 + 3x_4 -3\gamma \leq 0$

>> $3x_1 + 4x_2 + 5x_3 + 6x_4 -3\gamma \leq 0$

>> $x_1 + x_2 + x_3 + x_4 + 0 = 1$

>> $x_1,x_2,x_3,x_4\geq 0$

Thus the dual is:

> $\min y_5$

> s.t. $3y_1 + 3y_2 + 3y_3 + 3y_4 + y_5 \geq 0$

>> $y_1 + 4y_2 + 4y_3 + 4y_4 + y_5 \geq 0$

>> $y_1 + 2y_2 + 5y_3 + 5y_4 + y_5 \geq 0$

>> $y_1 + 2y_2 + 3y_3 + 6y_4 + y_5 \geq 0$

>> $-y_1 -2y_2 - 3y_3 -3 y_4 = -1$

>> $y_1,y_2,y_3,y_4\geq 0$

Thus the complementary slackness conditions are as follows:

> $(3x_1+x_2+x_3+x_4-\gamma)y_1=0$

> $(3x_1+4x_2+2x_3+2x_4-2\gamma)y_2=0$

> $(3x_1+4x_2+5x_3+3x_4-3\gamma)y_3=0$

> $(3x_1+4x_2+5x_3+6x_4-3\gamma)y_4=0$

> $(x_1+x_2+x_3+x_4-1)y_5=0$

(Note for the slack $c-A^Ty$, since this is equal to $0$ I am multiplying by $-1$ to make the copying over a little easier)

> $(3y_1+3y_2+3y_3+3y_4+y_5)x_1=0$ 

> $(y_1+4y_2+4y_3+4y_4+y_5)x_2=0$ 

> $(y_1+2y_2+5y_3+5y_4+y_5)x_3=0$ 

> $(y_1+2y_2+3y_3+6y_4+y_5)x_4=0$ 

> $(-y_1-2y_2-3y_3-3y_4+1)\gamma=0$ 


### d
```{python}
from docplex.mp.model import Model

mdl = Model()

y1 = mdl.continuous_var(name='y1', lb=0)
y2 = mdl.continuous_var(name='y2', lb=0)
y3 = mdl.continuous_var(name='y3', lb=0)
y4 = mdl.continuous_var(name='y4', lb=0)
y5 = mdl.continuous_var(name='y5', lb=-mdl.infinity, ub=mdl.infinity)

mdl.add_constraint(3*y1 + 3*y2 + 3*y3 + 3*y4 + y5 >= 0)
mdl.add_constraint(1*y1 + 4*y2 + 4*y3 + 4*y4 + y5 >= 0)
mdl.add_constraint(1*y1 + 2*y2 + 5*y3 + 5*y4 + y5 >= 0)
mdl.add_constraint(1*y1 + 2*y2 + 3*y3 + 6*y4 + y5 >= 0)
mdl.add_constraint(-y1 - 2*y2 - 3*y3 - 3*y4  == -1)

mdl.minimize(y5)

solution = mdl.solve()

print(mdl.export_as_lp_string())

print(solution)
```

This results in a $y^*$ as follows *rounded to 3 decimals by solver*:

$$
y^* =
\begin{pmatrix}
0.158 \\
0.105 \\
0.070 \\
0.140 \\
-1.421
\end{pmatrix}
$$

We can substitute the values of $y^*$ to our slackness conditions:

> $(3x_1+x_2+x_3+x_4-\gamma)(0.158)=0$

> $(3x_1+4x_2+2x_3+2x_4-2\gamma)(0.105)=0$

> $(3x_1+4x_2+5x_3+3x_4-3\gamma)(0.07)=0$

> $(3x_1+4x_2+5x_3+6x_4-3\gamma)(0.14)=0$

> $(x_1+x_2+x_3+x_4-1)(-1.421)=0$

> $(3(0.158)+3(0.105)+3(0.07)+3(0.14)-1.421)x_1=0$ 

>> $\rightarrow\approx (0)x_1 =0$

> $((0.158)+4(0.105)+4(0.07)+4(0.14)+(-1.421))x_2=0$ 

>> $\rightarrow\approx (0)x_2 =0$

> $((0.158)+2(0.105)+5(0.07)+5(0.14)+(-1.421))x_3=0$ 

>> $\rightarrow\approx (0)x_3 =0$

> $((0.158)+2(0.105)+3(0.07)+6(0.14)+(-1.421))x_4=0$ 

>> $\rightarrow\approx (0)x_4 =0$

> $(-(0.158)-2(0.105)-3(0.07)-3(0.14)+1)\gamma=0$ 

>> $\rightarrow\approx (0)\gamma =0$

> *Note $\approx$ was used to denote any rounding errors*

> Any slackness conditions that did not immediately go to $0$ can be rewritten as a system of linear equations $Ax^*=b$ where:

$$
A=\begin{pmatrix}
3 & 1 & 1 & 1 & -1 \\
3 & 4 & 2 & 2 & -2 \\
3 & 4 & 5 & 3 & -3 \\
3 & 4 & 5 & 6 & -3 \\
1 & 1 & 1 & 1 & 0
\end{pmatrix}
,x^*=\begin{pmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
\gamma 
\end{pmatrix}
,b=\begin{pmatrix}
0 \\
0 \\
0 \\
0 \\
1
\end{pmatrix}
$$

Solving this system we get the following steps:

$$
\makeatletter
\renewcommand*\env@matrix[1][*\c@MaxMatrixCols c]{%
  \hskip -\arraycolsep
  \let\@ifnextchar\new@ifnextchar
  \array{#1}}
\makeatother
\begin{pmatrix}[ccccc|c]
3 & 1 & 1 & 1 & -1 & 0 \\
3 & 4 & 2 & 2 & -2 & 0 \\
3 & 4 & 5 & 3 & -3 & 0 \\
3 & 4 & 5 & 6 & -3 & 0 \\
1 & 1 & 1 & 1 & 0 & 1
\end{pmatrix}
=
\begin{pmatrix}[ccccc|c]
3 & 1 & 1 & 1 & -1 & 0 \\
0 & 3 & 1 & 1 & -1 & 0 \\
0 & 3 & 4 & 2 & -2 & 0 \\
0 & 3 & 4 & 5 & -2 & 0 \\
0 & \frac23 & \frac23 & \frac23 & \frac13 & 1
\end{pmatrix}
=
\begin{pmatrix}[ccccc|c]
3 & 1 & 1 & 1 & -1 & 0 \\
0 & 3 & 1 & 1 & -1 & 0 \\
0 & 0 & 3 & 1 & -1 & 0 \\
0 & 0 & 3 & 4 & -1 & 0 \\
0 & 0 & \frac49 & \frac49 & \frac59 & 1
\end{pmatrix}
$$

$$
\makeatletter
\renewcommand*\env@matrix[1][*\c@MaxMatrixCols c]{%
  \hskip -\arraycolsep
  \let\@ifnextchar\new@ifnextchar
  \array{#1}}
\makeatother
\rightarrow =
\begin{pmatrix}[ccccc|c]
3 & 1 & 1 & 1 & -1 & 0 \\
0 & 3 & 1 & 1 & -1 & 0 \\
0 & 0 & 3 & 1 & -1 & 0 \\
0 & 0 & 0 & 3 & 0 & 0 \\
0 & 0 & 0 & \frac8{27} & \frac{19}{27} & 1
\end{pmatrix}
=
\begin{pmatrix}[ccccc|c]
3 & 1 & 1 & 1 & -1 & 0 \\
0 & 3 & 1 & 1 & -1 & 0 \\
0 & 0 & 3 & 1 & -1 & 0 \\
0 & 0 & 0 & 3 & 0 & 0 \\
0 & 0 & 0 & 0 & \frac{19}{27} & 1
\end{pmatrix}
$$

> Thus it is clear from the final line that $\gamma=\frac{27}{19}$ and from the 2nd to last line that $x_4=0$

> Using this and line 3 that $x_3=\frac13 \gamma =\frac{9}{19}$ 

> Then we get $3x_2 = \gamma - x_3 \rightarrow x_2=\frac{6}{19}$

> Lastly $3x_1 = \gamma -x_3 -x_2 \rightarrow \frac{4}{19}$

Therefore we end up with $x^*,y^*$ as follows:

$$
y^* =
\begin{pmatrix}
0.158 \\
0.105 \\
0.070 \\
0.140 \\
-1.421
\end{pmatrix}
, x^* =
\begin{pmatrix}
\frac{4}{19} \\
\frac{6}{19} \\
\frac{9}{19} \\
0 \\
\frac{27}{19} 
\end{pmatrix}
$$

We can also see that by strong duality these solutions result in their objective values being $-1.421$ (or $\frac{-27}{19}$ and assuming our objective is $\max -\gamma$) and equal. Thus these solutions are optimal.


## 5
### a
$A=\{(1,2),(2,3),(3,4),(4,2)\}$

$c(A)=\{(1,2),(1,4),(2,3),(2,4),(3,4)\}$

$\min \sum_{h=1}^4 y_h$

s.t. $x_{1h},x_{2h},x_{3h},x_{4h} \leq y_h, (h=\{1,2,3,4\})$

> $x_{1h} + x_{2h} \leq 1, (h=\{1,2,3,4\})$

> $x_{1h} + x_{4h} \leq 1, (h=\{1,2,3,4\})$

> $x_{2h} + x_{3h} \leq 1, (h=\{1,2,3,4\})$

> $x_{2h} + x_{4h} \leq 1, (h=\{1,2,3,4\})$

> $x_{3h} + x_{4h} \leq 1, (h=\{1,2,3,4\})$

> $\sum_{h=1}^4 x_{1h} = 1$

> $\sum_{h=1}^4 x_{2h} = 1$

> $\sum_{h=1}^4 x_{3h} = 1$

> $\sum_{h=1}^4 x_{4h} = 1$

> $0 \leq x_{Ih}, y_{Ih} \leq 1, (I\in A, h=\{1,2,3,4\})$

NEED TO FINISH

# HW 3
## 1
### a

### b

### c

## 2


## 3


## 4
Let $m=|E|,n=|V|$, so $A$ is a $(m+2n)\times n$ matrix. We get this from the first set of constraints in our LP is $x_i+x_j \leq 1, ((i,j)\in E)$ being of size $m$, then $x_i+\sum_{j:(j,i)\in E} x_j \geq 1, (i\in V)$ being of size $n$ and $x_i\leq 1$ being of size $n$.

Thus our dual will have $m+2n$ variables and $n$ constraints. 

For a variable $x_i$ in the dual, it appears in the first $m$ constraints when $i:(i,j)\in E\cup (j,i)\in E$. Similarly $x_i$ appears in the next $n$ constraints if there exists an edge from $i$ to $j$ or if $i=j$. For the last $n$ constraints, $x_i$ appears only once

Thus our dual is formulated as:



## 5
### a
Omit, Moved to HW4

### b

### c

### d-j
Omit, Moved to HW4

