---
format: pdf
---


# 1
## (i) (1 pt) What does the scatter plot of yields versus nitrogen suggest?

## (ii) (1 pt) Fit separate linear first-order and second-order models with yield as the response and nitrogen as the predictor.

## (iii) (2 pt) Is the second-order model a better fit?

## (iv) (2 pt) What can you conclude about the relationship between yield and nitrogen?


# 2
## (i) (1 pt) Fit a multiple linear regression with ratio as the response and age, gender, and frame as predictors.

## (ii) (2 pt) Is there a significant difference in the ratio of HDL between males and females?

## (iii) (2pt) Report and interpret the coefficients for frame.

## (iv) (1 pt) Is there an interaction between gender and frame based on the interaction plot?

## (v) (1 pt) If yes, is the interaction effect between gender and frame significant at α “ 0.10?

# 3
## (i) (1 pt) Calculate the correlation matrix of the test scores.

## (ii) (1 pt) Does the correlation matrix suggest a possible multicollinearity problem for predicting job proficiency score (JPS) from the test scores?

## (iii) (1 pt) Fit a multiple linear regression model with JPS as the response and the test scores as the predictors.

## (iv) (1 pt) Compute the variance inflation factors for each of the model parameters in (iii).

## (v) (1 pt) What does the VIF suggest?

## (vi) (2 pt) Use a stepwise regression with AIC criterion to select the best model for predicting JPS.

